# Generated by Django 2.2.6 on 2019-12-27 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='Имя')),
                ('birth_year', models.SmallIntegerField(verbose_name='День рождения')),
                ('country', models.CharField(max_length=2, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_friend', models.CharField(max_length=20, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='PublishHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_house_name', models.CharField(max_length=30, verbose_name='Издательство')),
                ('publish_housse_sity', models.CharField(max_length=20, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13)),
                ('title', models.TextField(verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='О книге')),
                ('year_release', models.SmallIntegerField(verbose_name='Дата публикации')),
                ('copy_count', models.SmallIntegerField(default=1, verbose_name='Кол-во книг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Фото')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Author')),
                ('friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='p_library.Friend')),
                ('publish_house', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p_library.PublishHouse')),
            ],
        ),
    ]
