# Generated by Django 2.2.6 on 2019-12-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='Фото'),
        ),
    ]
