# Generated by Django 3.0.1 on 2019-12-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20191228_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_release',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
