# Generated by Django 3.0.1 on 2020-01-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20191228_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_release',
            field=models.CharField(max_length=20, verbose_name='Год публикации'),
        ),
    ]
